# Generated by Django 4.2.3 on 2023-07-31 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('especie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Anfibio',
            fields=[
                ('mascota_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mascotas.mascota')),
                ('tipo_piel', models.CharField(max_length=100)),
            ],
            bases=('mascotas.mascota',),
        ),
        migrations.CreateModel(
            name='Ave',
            fields=[
                ('mascota_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mascotas.mascota')),
                ('tipo_plumaje', models.CharField(max_length=100)),
            ],
            bases=('mascotas.mascota',),
        ),
        migrations.CreateModel(
            name='Reptil',
            fields=[
                ('mascota_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mascotas.mascota')),
                ('tipo_escamas', models.CharField(max_length=100)),
            ],
            bases=('mascotas.mascota',),
        ),
    ]
